import { IAddress } from "./address";
import { IBookshelf } from "./bookshelf";
import { ICommunity } from "./community";
import { IEntry } from "./entry";

export type IUser = {
  _id: string;
  id: string;
  name: string;
  surname: string;
  username: string;
  email: string;
  phoneNumber: string;
  occupation: string;
  image: string;
  bio: string;
  threads: IEntry[];
  onboarded: boolean;
  address: IAddress[];
  followers: IUser[];
  following: IUser[];
  communities: ICommunity[];
  bookshelf: IBookshelf[];
  createdDate: Date;
  updatedDate: Date;
  role: string;
  createdAt: Date;
  visibility: boolean;
  status: string;
};
